
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: facebookclone_development


test:
  <<: *default
  database: facebookclone_test


production:
  <<: *default
  database: facebookclone_production
  username: facebookclone
  password: <%= ENV['FACEBOOKCLONE_DATABASE_PASSWORD'] %>
